##creates a matrix and calculates its inverse to be cached for future computations
##1. Sets value of matrix
##2. Gets value of matrix
##3. Sets value of matrix inverse
##4. Gets value of matrix inverse

####function that stores list of functions to perform on matrix
makeCacheMatrix <- function(x = matrix()) { 
  ##input is matrix, but don't know dimensions yet
  
  ##where inverse will be stored, makes it so a placeholder for a future value
  inv <- NULL 
  
  ##defines function that changes matrix stored in main function makeCacheMatrix
  set <- function(y) { 
    ##subs matrix x with y, the input, in main function makeCacheMatrix;
    ##if x <- y, only substitute x with y in set function
    x <<- y  
            
    ##resets inv to NULL because old inverse no longer valid
    ##new inverse calculated through function cacheSolve
    inv <<- NULL                    
  }
  
  ##returns matrix x stored in main function makeCacheMatrix
  get <- function() x 
  
  ##functions setinverse and getinverse do NOT calculate the inverse
  ##stores value of input in variable inv in main function makeCacheMatrix
  setinverse <- function(solve) inv <<- solve 
  
  ##returns inverse inv
  getinverse <- function() inv 
  
  ##to store 4 functions in makeCacheMatrix, need function list() so when assign
  ##makeCacheMatrix to an object, the object has all 4 functions
  ##instead of a = set, etc., name columns with name of functions
  list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


##input of cacheSolve is object where makeCacheMatrix is stored
##calculates inverse of matrix created with makeCacheMatrix
cacheSolve <- function(x, ...) {
  ##assign inverse from makeCacheMatrix to inv
  inv <- x$getinverse() 
  
  ##first checks to see if an inverse has already been calculated
  if (!is.null(inv)) { 
    ##if inv is NOT NULL, then will use inv from makeCacheVector
    message("getting cached data")
    return(inv)
  }
  
  ##can think of this part as else; 
  ##if inverse not already calculated, calculates inverse of data and sets value  
  ##of inverse in cache via setinverse function
  
  ##if inv is NULL, will get matrix stored with makeCacheMatrix
  data <- x$get() 
  
  ##calculates inverse of matrix from makeCacheMatrix
  inv <- solve(data, ...) 
  
  ##stores calculated inverse in object generated by makeCacheMatrix
  x$setinverse(inv) 
  
  inv
}
