##example cachevector program from Assignment 2

##creating a vector to be cached for future computations
##1. Sets value of vector
##2. Gets value of vector
##3. Sets value of mean
##4. Gets value of mean

##function that stores list of functions to perform on vector
makeVector <- function(x = numeric()) { ##specifies x as a numeric vector, 
  ##but don't know length yet
  m <- NULL ##where mean will be stored, makes it so a placeholder for a future value
  set <- function(y) {#defines funct that changes vector stored in main funct
    x <<- y ##subs vector x with y, the input, in main function makeVector; 
    ##if x <- y, only substitute x with y in set function
    m <<- NULL ##resets m mean to NULL because old mean no longer valid; 
    ##new mean will be calculated through function cachemean
  }
  
  get <- function() x ##returns vector x stored in main function makeVector
  ##functions setmean and getmean do NOT calculate the mean
  setmean <- function(mean) m <<- mean ##stores value of input in variable m 
  ##in main function makeVector
  getmean <- function() m ##returns mean m
  
  ##to store 4 functions in makeVector, need function list() so when assign
  ##makeVector to an object, the object has all 4 functions
  ##instead of a = set, etc., name columns with name of functions
  list(set = set, get = get,
       setmean = setmean,
       getmean = getmean) 
}



##input of cachemean is object where makeVector is stored

##calculates mean of vector created with makeVector
##first checks to see if a mean has already been calculated
##if mean already calculated, gets mean from cache and skips computation
##if mean not already calculated, calculates mean of data and sets value of 
##mean in cache via setmean function

cachemean <- function(x, ...) { 
  m <- x$getmean() ##assigning the calculated mean from makeVector to m
  if (!is.null(m)) { ##if m is NOT NULL, then will use the calculated mean from 
    ##makeVector
    message("getting cached data")
    return(m)
  }
  ##can think of this part as else; if m was NULL, then need to calculate mean
  data <- x$get() ##if m is NULL, will get vector stored with makeVector
  m <- mean(data, ...) ##calculates mean of vector from makeVector
  x$setmean(m) ##stores calculated mean in object generated by makeVector
  m
}